scrape_configs:
  - job_name: 'workhorse'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.111.206:9100']
  - job_name: 'workstation'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          alias: postgres
  # - job_name: 'otel-collector'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['otel-collector:8889']
  #     - targets: ['otel-collector:8888']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
